const NAVIGATOR = {
    LOGIN_FLOW: 'LOGIN_FLOW',
    LANDING_FLOW: 'LANDING_FLOW'
};

const LOGIN_STACK = {
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    PASSWORD_RECOVERY_SCREEN: 'PASSWORD_RECOVERY_SCREEN'
};

const LANDING_STACK = {
    SETTINGS: 'SETTINGS',
    FIRST_STACK: 'FIRST_STACK',
    SECOND_STACK: 'SECOND_STACK',
    THIRD_STACK: 'THIRD_STACK',
    FOURTH_STACK: 'FOURTH_STACK'
};

const FIRST_STACK = {
    FIRST_SCREEN: 'FIRST_SCREEN',
    DETAIL_FIRST_SCREEN: 'DETAIL_FIRST_SCREEN'
};

const SECOND_STACK = {
    SECOND_SCREEN: 'SECOND_SCREEN',
    DETAIL_SECOND_SCREEN: 'DETAIL_SECOND_SCREEN'
};

const THIRD_STACK = {
    THIRD_SCREEN: 'THIRD_SCREEN'
}

const FOURTH_STACK = {
    FOURTH_SCREEN: 'FOURTH_SCREEN'
}

const DRAWER_LABEL ={
    LABEL_HOME:'Home',
    LABEL_SETTINGS: 'Settings',
    LABEL_LOGOUT: 'Log Out'
}

const TAB = {
    STACK1: 'TAB_STACK1',
    STACK2: 'TAB_STACK2',
    SCREEN3: 'TAB_SCREEN3',
    SCREEN4: 'TAB_SCREEN4'
};

export default{
    NAVIGATOR,
    LOGIN_STACK,
    LANDING_STACK,
    FIRST_STACK,
    SECOND_STACK,
    THIRD_STACK,
    FOURTH_STACK,
    TAB,
    DRAWER_LABEL
};